<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Clases__CLASSMETADATA__' => 0,
'App__Entity__Dotes__CLASSMETADATA__' => 1,
'App__Entity__Habilidades__CLASSMETADATA__' => 2,
'App__Entity__Habilidades5__CLASSMETADATA__' => 3,
'App__Entity__Hechizos__CLASSMETADATA__' => 4,
'App__Entity__ListaHechizos__CLASSMETADATA__' => 5,
'App__Entity__Pactos__CLASSMETADATA__' => 6,
'App__Entity__Razas__CLASSMETADATA__' => 7,
'App__Entity__Solicitudes__CLASSMETADATA__' => 8,
'App__Entity__Subclases__CLASSMETADATA__' => 9,
'App__Entity__Subrazas__CLASSMETADATA__' => 10,
'App__Entity__Trasfondo__CLASSMETADATA__' => 11,
'App__Entity__User__CLASSMETADATA__' => 12,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Clases',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ClasesRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nombre' => $o[2],
                        'Requisitos' => $o[3],
                        'Competencias' => $o[4],
                        'Salvaciones' => $o[5],
                        'HabilidadesAElegir' => $o[6],
                        'PuntosDeGolpe' => $o[7],
                        'Equipamiento' => $o[8],
                        'Autor' => $o[9],
                        'Validado' => $o[10],
                        'img' => $o[11],
                        'Magia' => $o[12],
                        'ipAddress' => $o[13],
                        'createdAt' => $o[14],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'Nombre',
                        'requisitos' => 'Requisitos',
                        'competencias' => 'Competencias',
                        'salvaciones' => 'Salvaciones',
                        'habilidades_aelegir' => 'HabilidadesAElegir',
                        'puntos_de_golpe' => 'PuntosDeGolpe',
                        'equipamiento' => 'Equipamiento',
                        'autor' => 'Autor',
                        'validado' => 'Validado',
                        'img' => 'img',
                        'magia' => 'Magia',
                        'ip_address' => 'ipAddress',
                        'created_at' => 'createdAt',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nombre' => 'nombre',
                        'Requisitos' => 'requisitos',
                        'Competencias' => 'competencias',
                        'Salvaciones' => 'salvaciones',
                        'HabilidadesAElegir' => 'habilidades_aelegir',
                        'PuntosDeGolpe' => 'puntos_de_golpe',
                        'Equipamiento' => 'equipamiento',
                        'Autor' => 'autor',
                        'Validado' => 'validado',
                        'img' => 'img',
                        'Magia' => 'magia',
                        'ipAddress' => 'ip_address',
                        'createdAt' => 'created_at',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'clases',
                    ],
                ],
                'idGenerator' => [
                    $o[15],
                ],
                'name' => [
                    'App\\Entity\\Clases',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'boolean',
                    'string',
                    'integer',
                    'string',
                    'datetime',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nombre',
                    'Requisitos',
                    'Competencias',
                    'Salvaciones',
                    'HabilidadesAElegir',
                    'PuntosDeGolpe',
                    'Equipamiento',
                    'Autor',
                    'Validado',
                    'img',
                    'Magia',
                    'ipAddress',
                    'createdAt',
                ],
                'columnName' => [
                    1 => 'id',
                    'nombre',
                    'requisitos',
                    'competencias',
                    'salvaciones',
                    'habilidades_aelegir',
                    'puntos_de_golpe',
                    'equipamiento',
                    'autor',
                    'validado',
                    'img',
                    'magia',
                    'ip_address',
                    'created_at',
                ],
                'length' => [
                    2 => 200,
                    2000,
                    999,
                    999,
                    999,
                    100,
                    999,
                    350,
                    11 => 2000,
                    13 => 255,
                ],
                'nullable' => [
                    11 => true,
                    14 => true,
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Dotes',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\DotesRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nombre' => $o[2],
                        'Descripcion' => $o[3],
                        'Requisitos' => $o[4],
                        'Beneficios' => $o[5],
                        'Validado' => $o[6],
                        'Autor' => $o[7],
                        'img' => $o[8],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'Nombre',
                        'descripcion' => 'Descripcion',
                        'requisitos' => 'Requisitos',
                        'beneficios' => 'Beneficios',
                        'validado' => 'Validado',
                        'autor' => 'Autor',
                        'img' => 'img',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nombre' => 'nombre',
                        'Descripcion' => 'descripcion',
                        'Requisitos' => 'requisitos',
                        'Beneficios' => 'beneficios',
                        'Validado' => 'validado',
                        'Autor' => 'autor',
                        'img' => 'img',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'dotes',
                    ],
                ],
                'idGenerator' => [
                    $o[9],
                ],
                'name' => [
                    'App\\Entity\\Dotes',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'boolean',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nombre',
                    'Descripcion',
                    'Requisitos',
                    'Beneficios',
                    'Validado',
                    'Autor',
                    'img',
                ],
                'columnName' => [
                    1 => 'id',
                    'nombre',
                    'descripcion',
                    'requisitos',
                    'beneficios',
                    'validado',
                    'autor',
                    'img',
                ],
                'length' => [
                    2 => 100,
                    999,
                    100,
                    200,
                    7 => 150,
                    999,
                ],
                'nullable' => [
                    4 => true,
                    true,
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Habilidades',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\HabilidadesRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nombre' => $o[2],
                        'Descripcion' => $o[3],
                        'Autor' => $o[4],
                        'Validado' => $o[5],
                        'Origen_ID' => $o[6],
                        'OrigenNivel' => $o[7],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'Nombre',
                        'descripcion' => 'Descripcion',
                        'autor' => 'Autor',
                        'validado' => 'Validado',
                        'origen_id' => 'Origen_ID',
                        'origen_nivel' => 'OrigenNivel',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nombre' => 'nombre',
                        'Descripcion' => 'descripcion',
                        'Autor' => 'autor',
                        'Validado' => 'validado',
                        'Origen_ID' => 'origen_id',
                        'OrigenNivel' => 'origen_nivel',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'habilidades',
                    ],
                ],
                'idGenerator' => [
                    $o[8],
                ],
                'name' => [
                    'App\\Entity\\Habilidades',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'boolean',
                    'string',
                    'integer',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nombre',
                    'Descripcion',
                    'Autor',
                    'Validado',
                    'Origen_ID',
                    'OrigenNivel',
                ],
                'columnName' => [
                    1 => 'id',
                    'nombre',
                    'descripcion',
                    'autor',
                    'validado',
                    'origen_id',
                    'origen_nivel',
                ],
                'length' => [
                    2 => 200,
                    9999,
                    200,
                    6 => 255,
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Habilidades5',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\HabilidadesRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nombre' => $o[2],
                        'Descripcion' => $o[3],
                        'Autor' => $o[4],
                        'Validado' => $o[5],
                        'Origen_ID' => $o[6],
                        'OrigenNivel' => $o[7],
                        'Nombre2' => $o[8],
                        'Descripcion2' => $o[9],
                        'Autor2' => $o[10],
                        'Validado2' => $o[11],
                        'Origen_ID2' => $o[12],
                        'OrigenNivel2' => $o[13],
                        'Nombre3' => $o[14],
                        'Descripcion3' => $o[15],
                        'Autor3' => $o[16],
                        'Validado3' => $o[17],
                        'Origen_ID3' => $o[18],
                        'OrigenNivel3' => $o[19],
                        'Nombre4' => $o[20],
                        'Descripcion4' => $o[21],
                        'Autor4' => $o[22],
                        'Validado4' => $o[23],
                        'Origen_ID4' => $o[24],
                        'OrigenNivel4' => $o[25],
                        'Nombre5' => $o[26],
                        'Descripcion5' => $o[27],
                        'Autor5' => $o[28],
                        'Validado5' => $o[29],
                        'Origen_ID5' => $o[30],
                        'OrigenNivel5' => $o[31],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'Nombre',
                        'descripcion' => 'Descripcion',
                        'autor' => 'Autor',
                        'validado' => 'Validado',
                        'origen_id' => 'Origen_ID',
                        'origen_nivel' => 'OrigenNivel',
                        'nombre2' => 'Nombre2',
                        'descripcion2' => 'Descripcion2',
                        'autor2' => 'Autor2',
                        'validado2' => 'Validado2',
                        'origen_id2' => 'Origen_ID2',
                        'origen_nivel2' => 'OrigenNivel2',
                        'nombre3' => 'Nombre3',
                        'descripcion3' => 'Descripcion3',
                        'autor3' => 'Autor3',
                        'validado3' => 'Validado3',
                        'origen_id3' => 'Origen_ID3',
                        'origen_nivel3' => 'OrigenNivel3',
                        'nombre4' => 'Nombre4',
                        'descripcion4' => 'Descripcion4',
                        'autor4' => 'Autor4',
                        'validado4' => 'Validado4',
                        'origen_id4' => 'Origen_ID4',
                        'origen_nivel4' => 'OrigenNivel4',
                        'nombre5' => 'Nombre5',
                        'descripcion5' => 'Descripcion5',
                        'autor5' => 'Autor5',
                        'validado5' => 'Validado5',
                        'origen_id5' => 'Origen_ID5',
                        'origen_nivel5' => 'OrigenNivel5',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nombre' => 'nombre',
                        'Descripcion' => 'descripcion',
                        'Autor' => 'autor',
                        'Validado' => 'validado',
                        'Origen_ID' => 'origen_id',
                        'OrigenNivel' => 'origen_nivel',
                        'Nombre2' => 'nombre2',
                        'Descripcion2' => 'descripcion2',
                        'Autor2' => 'autor2',
                        'Validado2' => 'validado2',
                        'Origen_ID2' => 'origen_id2',
                        'OrigenNivel2' => 'origen_nivel2',
                        'Nombre3' => 'nombre3',
                        'Descripcion3' => 'descripcion3',
                        'Autor3' => 'autor3',
                        'Validado3' => 'validado3',
                        'Origen_ID3' => 'origen_id3',
                        'OrigenNivel3' => 'origen_nivel3',
                        'Nombre4' => 'nombre4',
                        'Descripcion4' => 'descripcion4',
                        'Autor4' => 'autor4',
                        'Validado4' => 'validado4',
                        'Origen_ID4' => 'origen_id4',
                        'OrigenNivel4' => 'origen_nivel4',
                        'Nombre5' => 'nombre5',
                        'Descripcion5' => 'descripcion5',
                        'Autor5' => 'autor5',
                        'Validado5' => 'validado5',
                        'Origen_ID5' => 'origen_id5',
                        'OrigenNivel5' => 'origen_nivel5',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'habilidades5',
                    ],
                ],
                'idGenerator' => [
                    $o[32],
                ],
                'name' => [
                    'App\\Entity\\Habilidades5',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'boolean',
                    'string',
                    'integer',
                    'string',
                    'string',
                    'string',
                    'boolean',
                    'string',
                    'integer',
                    'string',
                    'string',
                    'string',
                    'boolean',
                    'string',
                    'integer',
                    'string',
                    'string',
                    'string',
                    'boolean',
                    'string',
                    'integer',
                    'string',
                    'string',
                    'string',
                    'boolean',
                    'string',
                    'integer',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nombre',
                    'Descripcion',
                    'Autor',
                    'Validado',
                    'Origen_ID',
                    'OrigenNivel',
                    'Nombre2',
                    'Descripcion2',
                    'Autor2',
                    'Validado2',
                    'Origen_ID2',
                    'OrigenNivel2',
                    'Nombre3',
                    'Descripcion3',
                    'Autor3',
                    'Validado3',
                    'Origen_ID3',
                    'OrigenNivel3',
                    'Nombre4',
                    'Descripcion4',
                    'Autor4',
                    'Validado4',
                    'Origen_ID4',
                    'OrigenNivel4',
                    'Nombre5',
                    'Descripcion5',
                    'Autor5',
                    'Validado5',
                    'Origen_ID5',
                    'OrigenNivel5',
                ],
                'columnName' => [
                    1 => 'id',
                    'nombre',
                    'descripcion',
                    'autor',
                    'validado',
                    'origen_id',
                    'origen_nivel',
                    'nombre2',
                    'descripcion2',
                    'autor2',
                    'validado2',
                    'origen_id2',
                    'origen_nivel2',
                    'nombre3',
                    'descripcion3',
                    'autor3',
                    'validado3',
                    'origen_id3',
                    'origen_nivel3',
                    'nombre4',
                    'descripcion4',
                    'autor4',
                    'validado4',
                    'origen_id4',
                    'origen_nivel4',
                    'nombre5',
                    'descripcion5',
                    'autor5',
                    'validado5',
                    'origen_id5',
                    'origen_nivel5',
                ],
                'length' => [
                    2 => 200,
                    2500,
                    200,
                    6 => 255,
                    8 => 200,
                    2500,
                    200,
                    12 => 255,
                    14 => 200,
                    2500,
                    200,
                    18 => 255,
                    20 => 200,
                    2500,
                    200,
                    24 => 255,
                    26 => 200,
                    2500,
                    200,
                    30 => 255,
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Hechizos',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\HechizosRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nombre' => $o[2],
                        'Descripcion' => $o[3],
                        'Nivel' => $o[4],
                        'Escuela' => $o[5],
                        'TiempoDeEjecucion' => $o[6],
                        'Rango' => $o[7],
                        'Componentes' => $o[8],
                        'Validado' => $o[9],
                        'Autor' => $o[10],
                        'Duracion' => $o[11],
                        'Zona_Efecto' => $o[12],
                        'img' => $o[13],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'Nombre',
                        'descripcion' => 'Descripcion',
                        'nivel' => 'Nivel',
                        'escuela' => 'Escuela',
                        'tiempo_de_ejecucion' => 'TiempoDeEjecucion',
                        'rango' => 'Rango',
                        'componentes' => 'Componentes',
                        'validado' => 'Validado',
                        'autor' => 'Autor',
                        'duracion' => 'Duracion',
                        'zona_efecto' => 'Zona_Efecto',
                        'img' => 'img',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nombre' => 'nombre',
                        'Descripcion' => 'descripcion',
                        'Nivel' => 'nivel',
                        'Escuela' => 'escuela',
                        'TiempoDeEjecucion' => 'tiempo_de_ejecucion',
                        'Rango' => 'rango',
                        'Componentes' => 'componentes',
                        'Validado' => 'validado',
                        'Autor' => 'autor',
                        'Duracion' => 'duracion',
                        'Zona_Efecto' => 'zona_efecto',
                        'img' => 'img',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'hechizos',
                    ],
                ],
                'idGenerator' => [
                    $o[14],
                ],
                'name' => [
                    'App\\Entity\\Hechizos',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'integer',
                    'string',
                    'boolean',
                    'string',
                    'string',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nombre',
                    'Descripcion',
                    'Nivel',
                    'Escuela',
                    'TiempoDeEjecucion',
                    'Rango',
                    'Componentes',
                    'Validado',
                    'Autor',
                    'Duracion',
                    'Zona_Efecto',
                    'img',
                ],
                'columnName' => [
                    1 => 'id',
                    'nombre',
                    'descripcion',
                    'nivel',
                    'escuela',
                    'tiempo_de_ejecucion',
                    'rango',
                    'componentes',
                    'validado',
                    'autor',
                    'duracion',
                    'zona_efecto',
                    'img',
                ],
                'length' => [
                    2 => 200,
                    999,
                    10,
                    100,
                    100,
                    8 => 999,
                    10 => 100,
                    100,
                    200,
                    999,
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\ListaHechizos',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ListaHechizosRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'lista_hechizos',
                    ],
                ],
                'associationMappings' => [
                    [
                        'clase_id' => $o[2],
                        'hechizo_id' => $o[4],
                    ],
                ],
                'idGenerator' => [
                    $o[8],
                ],
                'name' => [
                    'App\\Entity\\ListaHechizos',
                    3 => 'clase_id_id',
                    5 => 'lista_hechizos_hechizos',
                    'lista_hechizos_id',
                    'hechizos_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                ],
                'fieldName' => [
                    1 => 'id',
                ],
                'columnName' => [
                    1 => 'id',
                ],
                'cascade' => [
                    2 => [
                        'persist',
                        'remove',
                    ],
                ],
                'fetch' => [
                    2 => 2,
                    4 => 2,
                ],
                'sourceEntity' => [
                    2 => 'App\\Entity\\ListaHechizos',
                    4 => 'App\\Entity\\ListaHechizos',
                ],
                'sourceToTargetKeyColumns' => [
                    2 => [
                        'clase_id_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    2 => [
                        'id' => 'clase_id_id',
                    ],
                ],
                'joinColumns' => [
                    2 => [
                        $o[3],
                    ],
                    5 => [
                        $o[6],
                    ],
                ],
                'joinColumnFieldNames' => [
                    2 => [
                        'clase_id_id' => 'clase_id_id',
                    ],
                ],
                'unique' => [
                    3 => true,
                ],
                'nullable' => [
                    3 => false,
                ],
                'referencedColumnName' => [
                    3 => 'id',
                    6 => 'id',
                    'id',
                ],
                'isOnDeleteCascade' => [
                    4 => true,
                ],
                'joinTable' => [
                    4 => $o[5],
                ],
                'joinTableColumns' => [
                    4 => [
                        'lista_hechizos_id',
                        'hechizos_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    4 => [
                        'lista_hechizos_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    4 => [
                        'hechizos_id' => 'id',
                    ],
                ],
                'inverseJoinColumns' => [
                    5 => [
                        $o[7],
                    ],
                ],
                'onDelete' => [
                    6 => 'CASCADE',
                    'CASCADE',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    2 => 'clase_id',
                    4 => 'hechizo_id',
                ],
                'targetEntity' => [
                    2 => 'App\\Entity\\Clases',
                    4 => 'App\\Entity\\Hechizos',
                ],
            ],
        ],
        $o[0],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Pactos',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\PactosRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nombre' => $o[2],
                        'Descripción' => $o[3],
                        'nivel_1' => $o[4],
                        'nivel_2' => $o[5],
                        'nivel_3' => $o[6],
                        'nivel_4' => $o[7],
                        'nivel_5' => $o[8],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'Nombre',
                        'descripción' => 'Descripción',
                        'nivel_1' => 'nivel_1',
                        'nivel_2' => 'nivel_2',
                        'nivel_3' => 'nivel_3',
                        'nivel_4' => 'nivel_4',
                        'nivel_5' => 'nivel_5',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nombre' => 'nombre',
                        'Descripción' => 'descripción',
                        'nivel_1' => 'nivel_1',
                        'nivel_2' => 'nivel_2',
                        'nivel_3' => 'nivel_3',
                        'nivel_4' => 'nivel_4',
                        'nivel_5' => 'nivel_5',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'pactos',
                    ],
                ],
                'idGenerator' => [
                    $o[9],
                ],
                'name' => [
                    'App\\Entity\\Pactos',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'integer',
                    'integer',
                    'integer',
                    'integer',
                    'integer',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nombre',
                    'Descripción',
                    'nivel_1',
                    'nivel_2',
                    'nivel_3',
                    'nivel_4',
                    'nivel_5',
                ],
                'columnName' => [
                    1 => 'id',
                    'nombre',
                    'descripción',
                    'nivel_1',
                    'nivel_2',
                    'nivel_3',
                    'nivel_4',
                    'nivel_5',
                ],
                'length' => [
                    2 => 150,
                    999,
                ],
            ],
        ],
        $o[0],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Razas',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\RazasRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nombre' => $o[2],
                        'Descripcion' => $o[3],
                        'Fuerza' => $o[4],
                        'Destreza' => $o[5],
                        'Constitucion' => $o[6],
                        'Inteligencia' => $o[7],
                        'Sabiduria' => $o[8],
                        'Carisma' => $o[9],
                        'Autor' => $o[10],
                        'Velocidad' => $o[11],
                        'AtaqueDesarmado' => $o[12],
                        'Validado' => $o[13],
                        'img' => $o[14],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'Nombre',
                        'descripcion' => 'Descripcion',
                        'fuerza' => 'Fuerza',
                        'destreza' => 'Destreza',
                        'constitucion' => 'Constitucion',
                        'inteligencia' => 'Inteligencia',
                        'sabiduria' => 'Sabiduria',
                        'carisma' => 'Carisma',
                        'autor' => 'Autor',
                        'velocidad' => 'Velocidad',
                        'ataque_desarmado' => 'AtaqueDesarmado',
                        'validado' => 'Validado',
                        'img' => 'img',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nombre' => 'nombre',
                        'Descripcion' => 'descripcion',
                        'Fuerza' => 'fuerza',
                        'Destreza' => 'destreza',
                        'Constitucion' => 'constitucion',
                        'Inteligencia' => 'inteligencia',
                        'Sabiduria' => 'sabiduria',
                        'Carisma' => 'carisma',
                        'Autor' => 'autor',
                        'Velocidad' => 'velocidad',
                        'AtaqueDesarmado' => 'ataque_desarmado',
                        'Validado' => 'validado',
                        'img' => 'img',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'razas',
                    ],
                ],
                'idGenerator' => [
                    $o[15],
                ],
                'name' => [
                    'App\\Entity\\Razas',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'integer',
                    'string',
                    'boolean',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nombre',
                    'Descripcion',
                    'Fuerza',
                    'Destreza',
                    'Constitucion',
                    'Inteligencia',
                    'Sabiduria',
                    'Carisma',
                    'Autor',
                    'Velocidad',
                    'AtaqueDesarmado',
                    'Validado',
                    'img',
                ],
                'columnName' => [
                    1 => 'id',
                    'nombre',
                    'descripcion',
                    'fuerza',
                    'destreza',
                    'constitucion',
                    'inteligencia',
                    'sabiduria',
                    'carisma',
                    'autor',
                    'velocidad',
                    'ataque_desarmado',
                    'validado',
                    'img',
                ],
                'length' => [
                    2 => 200,
                    999,
                    2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    200,
                    12 => 999,
                    14 => 999,
                ],
            ],
        ],
        $o[0],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Solicitudes',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\SolicitudesRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Tipo' => $o[2],
                        'Insercion' => $o[3],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'tipo' => 'Tipo',
                        'insercion' => 'Insercion',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Tipo' => 'tipo',
                        'Insercion' => 'insercion',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'solicitudes',
                    ],
                ],
                'idGenerator' => [
                    $o[4],
                ],
                'name' => [
                    'App\\Entity\\Solicitudes',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'datetime',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Tipo',
                    'Insercion',
                ],
                'columnName' => [
                    1 => 'id',
                    'tipo',
                    'insercion',
                ],
                'length' => [
                    2 => 100,
                ],
            ],
        ],
        $o[0],
        []
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Subclases',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\SubclasesRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nombre' => $o[2],
                        'Requisitos' => $o[3],
                        'clase_id' => $o[4],
                        'Autor' => $o[5],
                        'Validado' => $o[6],
                        'img' => $o[7],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'Nombre',
                        'requisitos' => 'Requisitos',
                        'clase_id' => 'clase_id',
                        'autor' => 'Autor',
                        'validado' => 'Validado',
                        'img' => 'img',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nombre' => 'nombre',
                        'Requisitos' => 'requisitos',
                        'clase_id' => 'clase_id',
                        'Autor' => 'autor',
                        'Validado' => 'validado',
                        'img' => 'img',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'subclases',
                    ],
                ],
                'idGenerator' => [
                    $o[8],
                ],
                'name' => [
                    'App\\Entity\\Subclases',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'integer',
                    'string',
                    'boolean',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nombre',
                    'Requisitos',
                    'clase_id',
                    'Autor',
                    'Validado',
                    'img',
                ],
                'columnName' => [
                    1 => 'id',
                    'nombre',
                    'requisitos',
                    'clase_id',
                    'autor',
                    'validado',
                    'img',
                ],
                'length' => [
                    2 => 200,
                    999,
                    5 => 200,
                    7 => 999,
                ],
                'nullable' => [
                    3 => true,
                ],
            ],
        ],
        $o[0],
        []
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Subrazas',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\SubrazasRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nombre' => $o[2],
                        'Descripcion' => $o[3],
                        'raza_id' => $o[4],
                        'Fuerza' => $o[5],
                        'Destreza' => $o[6],
                        'Constitucion' => $o[7],
                        'Inteligencia' => $o[8],
                        'Sabiduria' => $o[9],
                        'Carisma' => $o[10],
                        'Autor' => $o[11],
                        'AtaqueDesarmado' => $o[12],
                        'Validado' => $o[13],
                        'img' => $o[14],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'Nombre',
                        'descripcion' => 'Descripcion',
                        'raza_id' => 'raza_id',
                        'fuerza' => 'Fuerza',
                        'destreza' => 'Destreza',
                        'constitucion' => 'Constitucion',
                        'inteligencia' => 'Inteligencia',
                        'sabiduria' => 'Sabiduria',
                        'carisma' => 'Carisma',
                        'autor' => 'Autor',
                        'ataque_desarmado' => 'AtaqueDesarmado',
                        'validado' => 'Validado',
                        'img' => 'img',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nombre' => 'nombre',
                        'Descripcion' => 'descripcion',
                        'raza_id' => 'raza_id',
                        'Fuerza' => 'fuerza',
                        'Destreza' => 'destreza',
                        'Constitucion' => 'constitucion',
                        'Inteligencia' => 'inteligencia',
                        'Sabiduria' => 'sabiduria',
                        'Carisma' => 'carisma',
                        'Autor' => 'autor',
                        'AtaqueDesarmado' => 'ataque_desarmado',
                        'Validado' => 'validado',
                        'img' => 'img',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'subrazas',
                    ],
                ],
                'idGenerator' => [
                    $o[15],
                ],
                'name' => [
                    'App\\Entity\\Subrazas',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'boolean',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nombre',
                    'Descripcion',
                    'raza_id',
                    'Fuerza',
                    'Destreza',
                    'Constitucion',
                    'Inteligencia',
                    'Sabiduria',
                    'Carisma',
                    'Autor',
                    'AtaqueDesarmado',
                    'Validado',
                    'img',
                ],
                'columnName' => [
                    1 => 'id',
                    'nombre',
                    'descripcion',
                    'raza_id',
                    'fuerza',
                    'destreza',
                    'constitucion',
                    'inteligencia',
                    'sabiduria',
                    'carisma',
                    'autor',
                    'ataque_desarmado',
                    'validado',
                    'img',
                ],
                'length' => [
                    2 => 200,
                    999,
                    5 => 2,
                    2,
                    2,
                    2,
                    2,
                    2,
                    200,
                    999,
                    14 => 999,
                ],
            ],
        ],
        $o[0],
        []
    );
},
11 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Trasfondo',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\TrasfondoRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'Nombre' => $o[2],
                        'Descripcion' => $o[3],
                        'Origen' => $o[4],
                        'Idiomas' => $o[5],
                        'ObjetosIniciales' => $o[6],
                        'Competencias' => $o[7],
                        'Validado' => $o[8],
                        'Autor' => $o[9],
                        'Plano' => $o[10],
                        'img' => $o[11],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'nombre' => 'Nombre',
                        'descripcion' => 'Descripcion',
                        'origen' => 'Origen',
                        'idiomas' => 'Idiomas',
                        'objetos_iniciales' => 'ObjetosIniciales',
                        'competencias' => 'Competencias',
                        'validado' => 'Validado',
                        'autor' => 'Autor',
                        'plano' => 'Plano',
                        'img' => 'img',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'Nombre' => 'nombre',
                        'Descripcion' => 'descripcion',
                        'Origen' => 'origen',
                        'Idiomas' => 'idiomas',
                        'ObjetosIniciales' => 'objetos_iniciales',
                        'Competencias' => 'competencias',
                        'Validado' => 'validado',
                        'Autor' => 'autor',
                        'Plano' => 'plano',
                        'img' => 'img',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'trasfondo',
                    ],
                ],
                'idGenerator' => [
                    $o[12],
                ],
                'name' => [
                    'App\\Entity\\Trasfondo',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'string',
                    'boolean',
                    'string',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'Nombre',
                    'Descripcion',
                    'Origen',
                    'Idiomas',
                    'ObjetosIniciales',
                    'Competencias',
                    'Validado',
                    'Autor',
                    'Plano',
                    'img',
                ],
                'columnName' => [
                    1 => 'id',
                    'nombre',
                    'descripcion',
                    'origen',
                    'idiomas',
                    'objetos_iniciales',
                    'competencias',
                    'validado',
                    'autor',
                    'plano',
                    'img',
                ],
                'length' => [
                    2 => 200,
                    999,
                    100,
                    999,
                    999,
                    999,
                    9 => 200,
                    100,
                    999,
                ],
                'nullable' => [
                    5 => true,
                    true,
                    true,
                    10 => true,
                ],
            ],
        ],
        $o[0],
        []
    );
},
12 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\User',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\UserRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'username' => $o[2],
                        'roles' => $o[3],
                        'password' => $o[4],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'username' => 'username',
                        'roles' => 'roles',
                        'password' => 'password',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'username' => 'username',
                        'roles' => 'roles',
                        'password' => 'password',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                        'quoted' => true,
                        'uniqueConstraints' => [
                            'UNIQ_IDENTIFIER_USERNAME' => [
                                'fields' => [
                                    'username',
                                ],
                            ],
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[5],
                ],
                'name' => [
                    'App\\Entity\\User',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'json',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'username',
                    'roles',
                    'password',
                ],
                'columnName' => [
                    1 => 'id',
                    'username',
                    'roles',
                    'password',
                ],
                'length' => [
                    2 => 180,
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
