<?php

namespace ContainerSZWxXRj;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRazasRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RazasRepository' shared autowired service.
     *
     * @return \App\Repository\RazasRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RazasRepository'] = new \App\Repository\RazasRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
