<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKBzYDnX\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKBzYDnX/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKBzYDnX.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKBzYDnX\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKBzYDnX\App_KernelProdContainer([
    'container.build_hash' => 'KBzYDnX',
    'container.build_id' => 'e799ff4b',
    'container.build_time' => 1717256950,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKBzYDnX');
