<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQAKBGmO\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQAKBGmO/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQAKBGmO.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQAKBGmO\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQAKBGmO\App_KernelProdContainer([
    'container.build_hash' => 'QAKBGmO',
    'container.build_id' => 'bf9d287f',
    'container.build_time' => 1717410853,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQAKBGmO');
