<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAqx23rk\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAqx23rk/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAqx23rk.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAqx23rk\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAqx23rk\App_KernelProdContainer([
    'container.build_hash' => 'Aqx23rk',
    'container.build_id' => '48f1922a',
    'container.build_time' => 1717256503,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAqx23rk');
