<?php

namespace ContainerKBzYDnX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHechizosTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\HechizosType' shared autowired service.
     *
     * @return \App\Form\HechizosType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\HechizosType'] = new \App\Form\HechizosType(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
