<?php

namespace ContainerLS4qEPp;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabilidadesType1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\HabilidadesType1' shared autowired service.
     *
     * @return \App\Form\HabilidadesType1
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/HabilidadesType1.php';

        return $container->privates['App\\Form\\HabilidadesType1'] = new \App\Form\HabilidadesType1();
    }
}
