<?php

namespace ContainerKJZdRG2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClasesTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ClasesType' shared autowired service.
     *
     * @return \App\Form\ClasesType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ClasesType'] = new \App\Form\ClasesType(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
