<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUzKUnxt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUzKUnxt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUzKUnxt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUzKUnxt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUzKUnxt\App_KernelDevDebugContainer([
    'container.build_hash' => 'UzKUnxt',
    'container.build_id' => 'cb32262e',
    'container.build_time' => 1711641184,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUzKUnxt');
