<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3OXj4TR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3OXj4TR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3OXj4TR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3OXj4TR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3OXj4TR\App_KernelDevDebugContainer([
    'container.build_hash' => '3OXj4TR',
    'container.build_id' => '835b52cd',
    'container.build_time' => 1712599203,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3OXj4TR');
