<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT62v3Nd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT62v3Nd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT62v3Nd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT62v3Nd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT62v3Nd\App_KernelDevDebugContainer([
    'container.build_hash' => 'T62v3Nd',
    'container.build_id' => 'f29c77b7',
    'container.build_time' => 1714577480,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT62v3Nd');
