<?php

namespace ContainerUmImLL8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRazasTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\RazasType' shared autowired service.
     *
     * @return \App\Form\RazasType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\RazasType'] = new \App\Form\RazasType(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
