<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Clases extends \App\Entity\Clases implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Autor' => [parent::class, 'Autor', null],
        "\0".parent::class."\0".'Competencias' => [parent::class, 'Competencias', null],
        "\0".parent::class."\0".'Equipamiento' => [parent::class, 'Equipamiento', null],
        "\0".parent::class."\0".'HabilidadesAElegir' => [parent::class, 'HabilidadesAElegir', null],
        "\0".parent::class."\0".'Magia' => [parent::class, 'Magia', null],
        "\0".parent::class."\0".'Nombre' => [parent::class, 'Nombre', null],
        "\0".parent::class."\0".'PuntosDeGolpe' => [parent::class, 'PuntosDeGolpe', null],
        "\0".parent::class."\0".'Requisitos' => [parent::class, 'Requisitos', null],
        "\0".parent::class."\0".'Salvaciones' => [parent::class, 'Salvaciones', null],
        "\0".parent::class."\0".'Validado' => [parent::class, 'Validado', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'img' => [parent::class, 'img', null],
        "\0".parent::class."\0".'ipAddress' => [parent::class, 'ipAddress', null],
        'Autor' => [parent::class, 'Autor', null],
        'Competencias' => [parent::class, 'Competencias', null],
        'Equipamiento' => [parent::class, 'Equipamiento', null],
        'HabilidadesAElegir' => [parent::class, 'HabilidadesAElegir', null],
        'Magia' => [parent::class, 'Magia', null],
        'Nombre' => [parent::class, 'Nombre', null],
        'PuntosDeGolpe' => [parent::class, 'PuntosDeGolpe', null],
        'Requisitos' => [parent::class, 'Requisitos', null],
        'Salvaciones' => [parent::class, 'Salvaciones', null],
        'Validado' => [parent::class, 'Validado', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'id' => [parent::class, 'id', null],
        'img' => [parent::class, 'img', null],
        'ipAddress' => [parent::class, 'ipAddress', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
