<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Habilidades5 extends \App\Entity\Habilidades5 implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Autor' => [parent::class, 'Autor', null],
        "\0".parent::class."\0".'Autor2' => [parent::class, 'Autor2', null],
        "\0".parent::class."\0".'Autor3' => [parent::class, 'Autor3', null],
        "\0".parent::class."\0".'Autor4' => [parent::class, 'Autor4', null],
        "\0".parent::class."\0".'Autor5' => [parent::class, 'Autor5', null],
        "\0".parent::class."\0".'Descripcion' => [parent::class, 'Descripcion', null],
        "\0".parent::class."\0".'Descripcion2' => [parent::class, 'Descripcion2', null],
        "\0".parent::class."\0".'Descripcion3' => [parent::class, 'Descripcion3', null],
        "\0".parent::class."\0".'Descripcion4' => [parent::class, 'Descripcion4', null],
        "\0".parent::class."\0".'Descripcion5' => [parent::class, 'Descripcion5', null],
        "\0".parent::class."\0".'Nombre' => [parent::class, 'Nombre', null],
        "\0".parent::class."\0".'Nombre2' => [parent::class, 'Nombre2', null],
        "\0".parent::class."\0".'Nombre3' => [parent::class, 'Nombre3', null],
        "\0".parent::class."\0".'Nombre4' => [parent::class, 'Nombre4', null],
        "\0".parent::class."\0".'Nombre5' => [parent::class, 'Nombre5', null],
        "\0".parent::class."\0".'OrigenNivel' => [parent::class, 'OrigenNivel', null],
        "\0".parent::class."\0".'OrigenNivel2' => [parent::class, 'OrigenNivel2', null],
        "\0".parent::class."\0".'OrigenNivel3' => [parent::class, 'OrigenNivel3', null],
        "\0".parent::class."\0".'OrigenNivel4' => [parent::class, 'OrigenNivel4', null],
        "\0".parent::class."\0".'OrigenNivel5' => [parent::class, 'OrigenNivel5', null],
        "\0".parent::class."\0".'Origen_ID' => [parent::class, 'Origen_ID', null],
        "\0".parent::class."\0".'Origen_ID2' => [parent::class, 'Origen_ID2', null],
        "\0".parent::class."\0".'Origen_ID3' => [parent::class, 'Origen_ID3', null],
        "\0".parent::class."\0".'Origen_ID4' => [parent::class, 'Origen_ID4', null],
        "\0".parent::class."\0".'Origen_ID5' => [parent::class, 'Origen_ID5', null],
        "\0".parent::class."\0".'Validado' => [parent::class, 'Validado', null],
        "\0".parent::class."\0".'Validado2' => [parent::class, 'Validado2', null],
        "\0".parent::class."\0".'Validado3' => [parent::class, 'Validado3', null],
        "\0".parent::class."\0".'Validado4' => [parent::class, 'Validado4', null],
        "\0".parent::class."\0".'Validado5' => [parent::class, 'Validado5', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'Autor' => [parent::class, 'Autor', null],
        'Autor2' => [parent::class, 'Autor2', null],
        'Autor3' => [parent::class, 'Autor3', null],
        'Autor4' => [parent::class, 'Autor4', null],
        'Autor5' => [parent::class, 'Autor5', null],
        'Descripcion' => [parent::class, 'Descripcion', null],
        'Descripcion2' => [parent::class, 'Descripcion2', null],
        'Descripcion3' => [parent::class, 'Descripcion3', null],
        'Descripcion4' => [parent::class, 'Descripcion4', null],
        'Descripcion5' => [parent::class, 'Descripcion5', null],
        'Nombre' => [parent::class, 'Nombre', null],
        'Nombre2' => [parent::class, 'Nombre2', null],
        'Nombre3' => [parent::class, 'Nombre3', null],
        'Nombre4' => [parent::class, 'Nombre4', null],
        'Nombre5' => [parent::class, 'Nombre5', null],
        'OrigenNivel' => [parent::class, 'OrigenNivel', null],
        'OrigenNivel2' => [parent::class, 'OrigenNivel2', null],
        'OrigenNivel3' => [parent::class, 'OrigenNivel3', null],
        'OrigenNivel4' => [parent::class, 'OrigenNivel4', null],
        'OrigenNivel5' => [parent::class, 'OrigenNivel5', null],
        'Origen_ID' => [parent::class, 'Origen_ID', null],
        'Origen_ID2' => [parent::class, 'Origen_ID2', null],
        'Origen_ID3' => [parent::class, 'Origen_ID3', null],
        'Origen_ID4' => [parent::class, 'Origen_ID4', null],
        'Origen_ID5' => [parent::class, 'Origen_ID5', null],
        'Validado' => [parent::class, 'Validado', null],
        'Validado2' => [parent::class, 'Validado2', null],
        'Validado3' => [parent::class, 'Validado3', null],
        'Validado4' => [parent::class, 'Validado4', null],
        'Validado5' => [parent::class, 'Validado5', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
